name: royal_hotel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  get: ^4.6.6
  shared_preferences: ^2.3.3
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.2
  loading_plus: ^2.0.2
  awesome_notifications: ^0.10.0
  firebase_messaging: ^15.1.6
  package_info_plus: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  upgrader: ^11.3.0
  in_app_review: ^2.0.10
  encrypt: ^5.0.3
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  country_picker: ^2.0.27
  pinput: ^5.0.0
  card_swiper: ^3.0.1
  #  rive: ^0.13.3
  #  cached_network_image: ^3.3.1
  #  transparent_image: ^2.0.1
  #  image_cropper: ^5.0.1
  #  image_picker: ^1.0.7
  #  geolocator: ^11.0.0
  #  shimmer: ^3.0.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  import_sorter: ^4.6.0
  rename: ^3.0.2
  ########## import_sorter ##########
import_sorter:
  emojis: false
  comments: false

# dart run import_sorter:main
########## import_sorter ##########

########## rename ##########
#  dart pub global activate rename
#  rename getAppName --targets ios,android,macos,windows,linux
#  rename setAppName --targets ios,android,macos,windows,linux --value "App Name"
#  rename getBundleId --targets ios,android,macos,windows,linux
#  rename setBundleId --targets ios,android,macos,windows,linux --value "com.example.royalHotel"

########## rename ##########

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  #  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

#  flutter pub get
#  dart run flutter_launcher_icons

########## flutter_launcher_icons ##########

########## flutter_native_splash ##########
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/icons/app_icon.png
  #branding: assets/dart.png
  # bottom, bottomRight, bottomLeft
  #branding_mode: bottom
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    color: "#ffffff"
    image: assets/icons/app_icon.png
  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove
########## flutter_native_splash ##########

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    # - assets/gifs/
    # - assets/sounds/
    # - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 300
